trigger:
- master
pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build_FE
    displayName: Build Webapp
    dependsOn: []
    jobs:
      - job: Build
        steps:
          - publish: $(Build.SourcesDirectory)/src
            artifact: build
            displayName: 'Publish build artifact'

  - stage: Deploy_FE_Dev
    displayName: Deploy Webapp Dev
    dependsOn: Build_FE
    variables:
      - group: "Frontend"
    jobs:
    - deployment: Deploy_Frontend_Dev
      environment: dev
      displayName: Deploy Frontend Dev
      strategy:
        runOnce:
          deploy:
            steps:
              - download: none
              - checkout: self
              - task: DownloadPipelineArtifact@2
                displayName: 'Download artifact'
                inputs:
                  source: current
                  artifact: build
                  path: ./build

              - task: CopyFiles@2
                inputs:
                  sourceFolder: '$(Build.SourcesDirectory)'
                  contents: '$(Build.SourcesDirectory)/.azure/staticwebapp.config.json'
                  targetFolder: '$(Build.SourcesDirectory)/build'

              - task: AzureStaticWebApp@0
                inputs:
                  app_location: 'build'
                  skip_app_build: true
                env:
                  azure_static_web_apps_api_token: $(DEV_DEPLOYMENT_TOKEN)