trigger:
- master
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: "Frontend"

stages:
  - stage: Build_FE
    displayName: Build Webapp
    dependsOn: []
    jobs:
      - job: Build
        steps:
          - publish: $(Build.SourcesDirectory)/src
            artifact: build
            displayName: 'Publish build artifact'

  - stage: Deploy_FE_Dev
    displayName: Deploy Webapp Dev
    dependsOn: Build_FE
    jobs:
    - deployment: Deploy_Frontend_Dev
      environment: dev
      displayName: Deploy Frontend Dev
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - task: DownloadPipelineArtifact@2
                displayName: 'Download artifact'
                inputs:
                  source: current
                  artifact: build
                  path: '$(Build.SourcesDirectory)'

              - task: CopyFiles@2
                inputs:
                  sourceFolder: '$(Build.SourcesDirectory)'
                  contents: './azure/staticwebapp.config.json'
                  targetFolder: '$(Build.SourcesDirectory)/build'

              - task: AzureStaticWebApp@0
                inputs:
                  app_location: '/build'
                  azure_static_web_apps_api_token: $(deployment_token)
                env:
                  deployment_token: $(DEV_DEPLOYMENT_TOKEN)